global using Solution.WebAPI.Configurations;
global using Microsoft.AspNetCore.Identity;
global using Solution.Domain.Database;
global using Solution.Domain.Database.Entities;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.IdentityModel.Tokens;
global using Solution.Domain.Models.Settings;
global using System.Text;